### PR TITLE
Fix compatibility with new Clojurescript releases (>0.0.2755)

### LINKED ISSUE #43: ExceptionInfo: No such namespace: cljsjs.react at line 1
Using:

```clojure
[org.clojure/clojurescript "0.0-2760"]
[org.omcljs/om             "0.8.8"]
[com.cemerick/piggieback   "0.1.5"]
[weasel                    "0.5.0"]
```

I then run "cider-jack-in" from Emacs, get a normal repl, then:

```clojure
(require 'weasel.repl.websocket)

(cemerick.piggieback/cljs-repl
 :repl-env (weasel.repl.websocket/repl-env
            :ip "0.0.0.0" :port 9001))
```

which results in:

```clojure
Unhandled clojure.lang.ExceptionInfo
   No such namespace: cljsjs.react at line 1
   file:/Users/keith/.m2/repository/sablono/sablono/0.3.1/sablono-0.3.1.jar!/sablono/core.cljs
{:tag :cljs/analysis-error,
 :file
 "file:/Users/keith/.m2/repository/sablono/sablono/0.3.1/sablono-0.3.1.jar!/sablono/core.cljs",
 :line 1,
 :column 1}
```

According to David Nolen:

> Weasel and piggieback likely need to be changed to load foreign dependencies.

Not sure how much that helps, but this seems to have been experienced by a few people if the clojurescript mailing list is any indication.

A fellow sufferer fixed it via a hack:

https://github.com/darwin/weasel/commit/c2b5b963bcf10a7c341a4cbc8f21121d3adef6b0

if that helps any.

### PR DESCRIPTION
**Pull request by the-kenny**
The last few Clojurescript releases broke weasel when requiring namespaces. This patch backports necessary changes from ```cljs.browser.repl``` to weasel.

1992a25 gathers upstream (js) dependencies and passes them down to the compiler. Same approach as https://github.com/clojure/clojurescript/commit/5a353c418769cc6d4c212db87e5f51b9511f7c33#diff-0e96f4c891374eb4ed736a5bdbb1b07dR273

74aa18e monkey-patches ```goog.require``` to be a no-op, like https://github.com/clojure/clojurescript/commit/5a353c418769cc6d4c212db87e5f51b9511f7c33#diff-c706571c79101d1f03c9f7073570741eR112

This fixes #43 - but depends on a clojurescript-release containing http://dev.clojure.org/jira/browse/CLJS-1002 (which isn't fixed yet). This is necessary because weasel runs ```cljs.closure/get-upstream-deps``` from a non-main thread & the function uses the current Thread's classloader. The JIRA-ticket makes ```get-upstream-deps``` take an optional argument which is then used as the classloader.

### CODE REVIEW

File: src/clj/weasel/repl/websocket.clj [hunk 1]
```diff
@@ -39,7 +39,11 @@
 (defn repl-env
   "Returns a JS environment to pass to repl or piggieback"
   [& {:as opts}]
-  (let [compiler-env (env/default-compiler-env opts)
+  (let [ups-deps (cljsc/get-upstream-deps (java.lang.ClassLoader/getSystemClassLoader))
+        opts (assoc opts
+               :ups-libs (:libs ups-deps)
+               :ups-foreign-libs (:foreign-libs ups-deps))
+        compiler-env (env/default-compiler-env opts)
```
Comment (martinklepsch) [inline src/clj/weasel/repl/websocket.clj]: @the-kenny not sure if plain `assoc` is the right thing here. Potentially users might want to influence what's in behind these keywords.

**Comment by martinklepsch** [comment]
Looking good! :hand:

**Comment by martinklepsch** [comment]
After merging this we can probably close: #43, #42, #37(?), #35. 
I assume many of the other existing issues might also require new verification that they still exist.

File: src/clj/weasel/repl/websocket.clj (hunk 1 above)
Comment (the-kenny) [inline src/clj/weasel/repl/websocket.clj]: You're right - I haven't thought of this. Fix incoming.

**Comment by the-kenny** [comment]
#37 only partially - in ```in-ns``` stuff with cider is still broken. We should open another ticket for that.

**Comment by dirtyrottenscoundrel** [comment]
@the-kenny Actually, if you add:

    [org.clojure/tools.nrepl "0.2.7"]

to your project.clj, the `in-ns` problem should be resolved now. See the last post on #26.

**Comment by the-kenny** [comment]
The necessary fix for Clojurescript is now in master - we can merge this with the next Clojurescript-release (we just need to bump the version in ```:dependencies```)

**Comment by tomjakubowski** [comment]
Thanks for this! I'll review in a few hours and if it all looks good I'll merge with the next release.

**Comment by tomjakubowski** [comment]
Looks great to me! Works splendidly with Clojurescript master. Once they cut a release I'll merge this and  release with the appropriate dependencies bumped.

**Comment by bonkydog** [comment]
I found that passing the system classloader to get-upstream-deps fixes this: #45

**Comment by the-kenny** [comment]
@bonkydog That's exactly what this pull request does.

**Comment by tomjakubowski** [comment]
Thanks again for this! I've put a `0.6.0-SNAPSHOT` out and I'll cut a proper release shortly.

**Comment by bonkydog** [comment]
Sweet!  Thanks!
